### ISSUE TITLE
Crash If Output is Being Redirected

### ISSUE THREAD

**Issue by felixstorm** [Microsoft/Intune-Win32-App-Packaging-Tool#8]
The tool crashes if the output is being redirected. Output of `IntuneWinAppUtil -c SomeSample -s Setup.exe -o . -q > test.log`:
```
Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_CursorVisible(Boolean value)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```

This is problematic if the tool is being included in automatic (CI) systems when there is no way for the output to be captured (especially in conjunction with https://github.com/Microsoft/Intune-Win32-App-Packaging-Tool/issues/7)

**Comment by felixstorm** [comment]
moved to https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/issues/5
